# Generated by Django 2.2.5 on 2020-02-16 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_search_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name_plural': 'Searches'},
        ),
    ]
